# Generated by Django 4.2.11 on 2024-05-06 06:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='correo electronico')),
                ('es_empleado', models.BooleanField(default=False)),
                ('es_superuser', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Cargo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre de cargo')),
                ('descripcion', models.CharField(blank=True, max_length=200, null=True, verbose_name='Descripcion de cargo')),
            ],
        ),
        migrations.CreateModel(
            name='Contrato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, verbose_name='Nombre de contrato')),
                ('horas_semanales', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=100, null=True, verbose_name='nombre')),
                ('apellido', models.CharField(blank=True, max_length=100, null=True, verbose_name='apellido')),
                ('rut', models.CharField(blank=True, max_length=50, verbose_name='rut')),
                ('cargo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cargo', to='planificador.cargo')),
                ('contrato', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contrato', to='planificador.contrato')),
            ],
        ),
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='nombre de empresa')),
                ('rubro', models.CharField(blank=True, max_length=100, null=True, verbose_name='rubro')),
            ],
        ),
        migrations.CreateModel(
            name='Sucursal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre de sucursal')),
                ('direccion', models.CharField(max_length=200, verbose_name='Direccion de sucursal')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='planificador.empresa')),
            ],
        ),
        migrations.CreateModel(
            name='TipoJornada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_tipo', models.CharField(max_length=100, verbose_name='nombre tipo jornada')),
            ],
        ),
        migrations.CreateModel(
            name='Turno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('hora_inicio', models.TimeField()),
                ('hora_final', models.TimeField()),
                ('colacion', models.IntegerField()),
                ('tipo', models.SmallIntegerField(choices=[(1, 1), (2, 2), (3, 3)], default=1)),
                ('estado', models.SmallIntegerField(choices=[(1, 1), (2, 2)], default=1)),
                ('cargo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='planificador.cargo')),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='planificador.empleado')),
                ('sucursal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='planificador.sucursal')),
            ],
        ),
        migrations.CreateModel(
            name='Solicitud',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.SmallIntegerField(choices=[(1, 1), (2, 2), (3, 3)], default=1)),
                ('fecha', models.DateField()),
                ('estado', models.SmallIntegerField(choices=[(1, 1), (2, 2), (3, 3)], default=1)),
                ('comentario', models.TextField()),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='planificador.empleado')),
                ('turno', models.ManyToManyField(blank=True, related_name='turnos', to='planificador.turno')),
            ],
        ),
        migrations.AddField(
            model_name='empleado',
            name='sucursal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sucursal', to='planificador.sucursal'),
        ),
        migrations.AddField(
            model_name='empleado',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='usuario_empleado', to=settings.AUTH_USER_MODEL, verbose_name='Usuario al que esta vinculado'),
        ),
        migrations.AddField(
            model_name='contrato',
            name='empresa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='planificador.empresa'),
        ),
        migrations.AddField(
            model_name='contrato',
            name='tipo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='jornada', to='planificador.tipojornada'),
        ),
        migrations.AddField(
            model_name='cargo',
            name='empresa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='planificador.empresa'),
        ),
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rol', models.CharField(blank=True, max_length=50, null=True, verbose_name='rol')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='planificador.empresa')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='usuario_admin', to=settings.AUTH_USER_MODEL, verbose_name='Usuario al que esta vinculado')),
            ],
        ),
    ]
