# Generated by Django 4.2.11 on 2024-05-12 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planificador', '0002_rename_name_contrato_nombre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sucursal',
            name='direccion',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Direccion de sucursal'),
        ),
    ]
