# Generated by Django 4.2.11 on 2024-05-14 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planificador', '0003_alter_sucursal_direccion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitud',
            name='comentario',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='solicitud',
            name='fecha',
            field=models.DateField(blank=True, null=True),
        ),
    ]
